# Generated by Django 5.1.5 on 2025-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='purchase_link',
            field=models.URLField(blank=True),
        ),
    ]
